"""update  sessio  table

Revision ID: 7170c777ba32
Revises: c75f2d8abc29
Create Date: 2024-11-20 02:31:31.695713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7170c777ba32'
down_revision: Union[str, None] = 'c75f2d8abc29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('is_active', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'is_active')
    # ### end Alembic commands ###
