"""Update relation

Revision ID: b79152e895b9
Revises: 7170c777ba32
Create Date: 2024-11-28 02:04:54.358059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79152e895b9'
down_revision: Union[str, None] = '7170c777ba32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_id_session', 'chat_sessions', type_='foreignkey')
    op.create_foreign_key('fk_user_id_session', 'chat_sessions', 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('FK_messages_session', 'messages', type_='foreignkey')
    op.create_foreign_key('FK_messages_session', 'messages', 'chat_sessions', ['session_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK_messages_session', 'messages', type_='foreignkey')
    op.create_foreign_key('FK_messages_session', 'messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_user_id_session', 'chat_sessions', type_='foreignkey')
    op.create_foreign_key('fk_user_id_session', 'chat_sessions', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
