"""Added messages table

Revision ID: c75f2d8abc29
Revises: 07e58db02c8e
Create Date: 2024-11-18 01:22:38.913404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c75f2d8abc29'
down_revision: Union[str, None] = '07e58db02c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applied_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filter_action', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name='FK_messages_session', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('idx_messages_content_gin', 'messages', ['content'], unique=False, postgresql_using='gin')
    op.create_index('idx_messages_filters_gin', 'messages', ['applied_filters'], unique=False, postgresql_using='gin')
    op.create_index('idx_messages_session_timestamp', 'messages', ['session_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chat_sessions_created_at'), 'chat_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_updated_at'), 'chat_sessions', ['updated_at'], unique=False)
    op.create_unique_constraint(None, 'chat_sessions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='unique')
    op.drop_index(op.f('ix_chat_sessions_updated_at'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_created_at'), table_name='chat_sessions')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index('idx_messages_session_timestamp', table_name='messages')
    op.drop_index('idx_messages_filters_gin', table_name='messages', postgresql_using='gin')
    op.drop_index('idx_messages_content_gin', table_name='messages', postgresql_using='gin')
    op.drop_table('messages')
    # ### end Alembic commands ###
